# Generated by Django 3.2.25 on 2024-08-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectListeleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_select_kanun', models.JSONField(blank=True, default=list)),
                ('dynamic_select_ucret', models.JSONField(blank=True, default=list)),
                ('dynamic_select_yil', models.JSONField(blank=True, default=list)),
                ('dynamic_select_statu', models.JSONField(blank=True, default=list)),
                ('dynamic_select_engelli', models.JSONField(blank=True, default=list)),
                ('dynamic_select_egitim', models.JSONField(blank=True, default=list)),
                ('dynamic_select_agi', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
