# Generated by Django 3.2.25 on 2024-08-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_desc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WageParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('Birinci_Donem_Net_Asgari_Ucret', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Birinci_Donem_Brut_Ucret_Taban', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Birinci_Donem_Birinci_Vergi_Dilimi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Birinci_Donem_Ikinci_Vergi_Dilimi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Birinci_Donem_Ucuncu_Vergi_Dilimi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Birinci_Donem_Dorduncu_Vergi_Dilimi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Birinci_Donem_Besinci_Vergi_Dilimi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Birinci_Donem_Birinci_Derece_Engelli_Indirimi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Birinci_Donem_Ikinci_Derece_Engelli_Indirimi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Birinci_Donem_Ucuncu_Derece_Engelli_Indirimi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Birinci_Donem_Brut_Ucret_Tavan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Ikinci_Donem_Net_Asgari_Ucret', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Ikinci_Donem_Brut_Ucret_Taban', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Ikinci_Donem_Birinci_Vergi_Dilimi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Ikinci_Donem_Ikinci_Vergi_Dilimi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Ikinci_Donem_Ucuncu_Vergi_Dilimi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Ikinci_Donem_Dorduncu_Vergi_Dilimi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Ikinci_Donem_Besinci_Vergi_Dilimi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Ikinci_Donem_Birinci_Derece_Engelli_Indirimi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Ikinci_Donem_Ikinci_Derece_Engelli_Indirimi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Ikinci_Donem_Ucuncu_Derece_Engelli_Indirimi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Ikinci_Donem_Brut_Ucret_Tavan', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
