# Generated by Django 3.2.25 on 2024-08-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_desc', '0002_wageparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bordro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ay', models.CharField(max_length=50)),
                ('Donem_Brut_Toplam', models.FloatField()),
                ('Gunluk_Brut_Ucret', models.FloatField()),
                ('SGK_matrah', models.FloatField()),
                ('Isci_SGK', models.FloatField()),
                ('Isci_Issizlik', models.FloatField()),
                ('GVM', models.FloatField()),
                ('KGVM', models.FloatField()),
                ('gelir_vergisi', models.FloatField()),
                ('damga_vergisi', models.FloatField()),
                ('Net_Ucret', models.FloatField()),
                ('Maas', models.FloatField()),
                ('Isveren_SGK', models.FloatField()),
                ('Isveren_Issizlik', models.FloatField()),
                ('Normal_Maliyet', models.FloatField()),
                ('Hazine_yardimi', models.FloatField()),
                ('Hazine_Indirimi_Sonrasi_Maliyet', models.FloatField()),
                ('Vergi_Odenecek', models.FloatField()),
                ('Normal_SGK_Odenecek', models.FloatField()),
                ('Hazine_Indirimi_Sonrasi_SGK_Odenecek', models.FloatField()),
                ('agi', models.FloatField()),
                ('GV_Istisna', models.FloatField()),
                ('DV_Istisna', models.FloatField()),
                ('Asg_GVM', models.FloatField()),
                ('Kum_Asg_GV', models.FloatField()),
                ('_2Ay_Onceki_Devir', models.FloatField()),
                ('_1Ay_Onceki_Devir', models.FloatField()),
            ],
        ),
    ]
