# Generated by Django 3.2.25 on 2024-08-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_desc', '0003_bordro'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordro',
            name='session_key',
            field=models.CharField(default='default_session_key', max_length=255, unique=True),
        ),
    ]
