# Generated by Django 3.2.25 on 2024-08-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_desc', '0004_bordro_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordro',
            name='session_key',
            field=models.CharField(default='default_session_key', max_length=255),
        ),
    ]
