# Generated by Django 3.2.25 on 2024-08-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_desc', '0005_alter_bordro_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bordro',
            old_name='_1Ay_Onceki_Devir',
            new_name='BirAyOncekiDevir',
        ),
        migrations.RenameField(
            model_name='bordro',
            old_name='_2Ay_Onceki_Devir',
            new_name='IkiAyOncekiDevir',
        ),
    ]
