# Generated by Django 3.2.25 on 2024-08-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_desc', '0006_auto_20240826_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordro',
            name='time_stamp_key',
            field=models.CharField(default='default_time_stamp_key', max_length=255),
        ),
    ]
