# Generated by Django 3.2.25 on 2024-08-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_desc', '0008_auto_20240830_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bordro',
            name='session_key',
            field=models.CharField(db_index=True, default='default_session_key', max_length=255),
        ),
        migrations.AlterField(
            model_name='bordro',
            name='time_stamp_key',
            field=models.CharField(db_index=True, default='default_time_stamp_key', max_length=255),
        ),
    ]
